# Generated by Django 4.0.4 on 2022-04-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('profile_pic', models.ImageField(blank=True, default='/media/profile_pic.jpg', null=True, upload_to='image')),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('auth_provider', models.CharField(default='email', max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='unregistered_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='ankitdawadi@gmail.com', max_length=50)),
                ('contactno', models.CharField(default='9999999999', max_length=20)),
                ('full_name', models.CharField(default='Ankit Dawadi', max_length=50)),
                ('street_address', models.CharField(default='Kalanki', max_length=50)),
                ('city', models.CharField(default='Kathmandu', max_length=50)),
                ('province', models.CharField(default='Bagmati', max_length=50)),
                ('location_type', models.CharField(default='inside ringroad', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='web_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('activation_code', models.CharField(default='code', max_length=50)),
                ('forgetcode', models.CharField(max_length=50, null=True)),
                ('forgetCodeSentTime', models.CharField(max_length=50, null=True)),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='+977', max_length=10)),
                ('contactno1', models.CharField(default='9999999999', max_length=20)),
                ('contactno2', models.CharField(max_length=20, null=True)),
                ('addressline1', models.CharField(default='Kalanki', max_length=100)),
                ('addressline2', models.CharField(max_length=100, null=True)),
                ('latitude', models.FloatField(max_length=50, null=True)),
                ('longitude', models.FloatField(max_length=50, null=True)),
                ('city', models.CharField(default='Kathmandu', max_length=50)),
                ('province', models.CharField(default='Province 3', max_length=50)),
                ('location_type', models.CharField(default='inside ringroad', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.web_users')),
            ],
        ),
    ]
