# Generated by Django 4.0.4 on 2022-04-28 08:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(default='GD-Shop', max_length=60)),
                ('brandIcon', models.ImageField(default='logo.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='Men', max_length=60)),
                ('categoryIcon', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('uid', models.UUIDField(primary_key=True, serialize=False)),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('is_logged', models.BooleanField(default=False)),
                ('session_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSessionCartMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSessionWishListMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommonCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_picture', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='FestiveSeasonProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FestiveSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festive_season_name', models.CharField(blank=True, max_length=250, null=True)),
                ('festive_season_picture', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('festive_season_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='image_galleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_combination', models.CharField(blank=True, max_length=100, null=True)),
                ('small', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('image1', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('image2', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('image3', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='product_cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='product_variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(default='Size', max_length=250, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='product_variations_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationValue', models.CharField(default='Large', max_length=250, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='Shoes', max_length=250, null='False')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('categoryName', models.CharField(default='Men', max_length=60, null='False')),
                ('subcategoryName', models.CharField(default='Formal', max_length=60)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('description_short', models.TextField(blank=True, null=True)),
                ('previewImg', models.ImageField(default='logo.jpg', upload_to=products.models.upload_to, verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False)),
                ('price', models.FloatField(default=1000.0)),
                ('stock', models.IntegerField(default=50)),
                ('description1', models.TextField(blank=True, null=True)),
                ('description2', models.TextField(blank=True, null=True)),
                ('description3', models.TextField(blank=True, null=True)),
                ('features1', models.CharField(blank=True, max_length=250, null=True)),
                ('features2', models.CharField(blank=True, max_length=250, null=True)),
                ('features3', models.CharField(blank=True, max_length=250, null=True)),
                ('features4', models.CharField(blank=True, max_length=250, null=True)),
                ('features5', models.CharField(blank=True, max_length=250, null=True)),
                ('features6', models.CharField(blank=True, max_length=250, null=True)),
                ('features7', models.CharField(blank=True, max_length=250, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=150, null=True)),
                ('warranty', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products_combinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_string', models.CharField(default='Large-red', max_length=250, null='False')),
                ('sku', models.CharField(default='lr', max_length=250, null='False')),
                ('price', models.FloatField(default=2000.0)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('unique_string_id', models.CharField(default='aeeglrr', max_length=250)),
                ('availableStock', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='products_stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalstock', models.IntegerField(default=0)),
                ('unitPrice', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='suscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='info@gdshopnepal.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='variations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationName', models.CharField(default='Size', max_length=250, null='False')),
            ],
        ),
        migrations.CreateModel(
            name='variations_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variationValue', models.CharField(default='Large', max_length=250, null='False')),
                ('variation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variations')),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryName', models.CharField(default='Formal', max_length=60)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
