# Generated by Django 4.0.4 on 2022-04-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festiveseasonproducts',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
