# Generated by Django 4.0.4 on 2022-04-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_festiveseasonproducts_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festiveseasonproducts',
            name='is_active',
        ),
        migrations.AddField(
            model_name='festiveseasons',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festiveseasonproducts',
            name='festive_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festive_season', to='products.festiveseasons'),
        ),
    ]
